std::string JSON_ITEMS = "[\n"
                         "  {\n"
                         "    \"Category\": \"Rifle\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 101001,\n"
                         "        \"itemClass\": \"BP_Rifle_AKM_Wrapper_C_1\",\n"
                         "        \"itemName\": \"AKM\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 101002,\n"
                         "        \"itemClass\": \"BP_Rifle_M16A4_Wrapper_C_1\",\n"
                         "        \"itemName\": \"M16A4\",\n"
                         "        \"itemTextColor\": \"0xFFD1EEEE\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 101003,\n"
                         "        \"itemClass\": \"BP_Rifle_SCAR_Wrapper_C_1\",\n"
                         "        \"itemName\": \"SCAR-L\",\n"
                         "        \"itemTextColor\": \"0xFFD1EEEE\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 101004,\n"
                         "        \"itemClass\": \"BP_Rifle_M416_Wrapper_C_1\",\n"
                         "        \"itemName\": \"M416\",\n"
                         "        \"itemTextColor\": \"0xFFD1EEEE\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 101005,\n"
                         "        \"itemClass\": \"BP_Rifle_Groza_Wrapper_C_1\",\n"
                         "        \"itemName\": \"Groza\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 101006,\n"
                         "        \"itemClass\": \"BP_Rifle_AUG_Wrapper_C_1\",\n"
                         "        \"itemName\": \"AUG A3\",\n"
                         "        \"itemTextColor\": \"0xFFD1EEEE\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 101007,\n"
                         "        \"itemClass\": \"BP_Rifle_QBZ_Wrapper_C_1\",\n"
                         "        \"itemName\": \"QBZ\",\n"
                         "        \"itemTextColor\": \"0xFFD1EEEE\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 101008,\n"
                         "        \"itemClass\": \"BP_Rifle_M762_Wrapper_C_1\",\n"
                         "        \"itemName\": \"M762\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 101009,\n"
                         "        \"itemClass\": \"BP_Rifle_Mk47_Wrapper_C_1\",\n"
                         "        \"itemName\": \"Mk47 Mutant\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 101010,\n"
                         "        \"itemClass\": \"BP_Rifle_G36_Wrapper_C_1\",\n"
                         "        \"itemName\": \"G36C\",\n"
                         "        \"itemTextColor\": \"0xFFD1EEEE\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 101100,\n"
                         "        \"itemClass\": \"BP_Rifle_FAMAS_Wrapper_C_1\",\n"
                         "        \"itemName\": \"FAMAS\",\n"
                         "        \"itemTextColor\": \"0xFFD1EEEE\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 105001,\n"
                         "        \"itemClass\": \"BP_Other_M249_Wrapper_C_1\",\n"
                         "        \"itemName\": \"M249\",\n"
                         "        \"itemTextColor\": \"0xFFD1EEEE\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 105002,\n"
                         "        \"itemClass\": \"BP_Other_DP28_Wrapper_C_1\",\n"
                         "        \"itemName\": \"DP-28\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  },\n"
                         "  {\n"
                         "    \"Category\": \"Sub-MachineGun\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 102001,\n"
                         "        \"itemClass\": \"BP_MachineGun_Uzi_Wrapper_C_1\",\n"
                         "        \"itemName\": \"UZI\",\n"
                         "        \"itemTextColor\": \"0xFF919AFF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 102002,\n"
                         "        \"itemClass\": \"BP_MachineGun_UMP9_Wrapper_C_1\",\n"
                         "        \"itemName\": \"UMP45\",\n"
                         "        \"itemTextColor\": \"0xFFF8FAB9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 102003,\n"
                         "        \"itemClass\": \"BP_MachineGun_Vector_Wrapper_C_1\",\n"
                         "        \"itemName\": \"Vector\",\n"
                         "        \"itemTextColor\": \"0xFF919AFF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 102004,\n"
                         "        \"itemClass\": \"BP_MachineGun_TommyGun_Wrapper_C_1\",\n"
                         "        \"itemName\": \"Tompson SMG\",\n"
                         "        \"itemTextColor\": \"0xFFF8FAB9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 102005,\n"
                         "        \"itemClass\": \"BP_MachineGun_PP19_Wrapper_C_1\",\n"
                         "        \"itemName\": \"PP-19 Bizon\",\n"
                         "        \"itemTextColor\": \"0xFF919AFF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 102007,\n"
                         "        \"itemClass\": \"BP_MachineGun_MP5K_Wrapper_C_1\",\n"
                         "        \"itemName\": \"Skorpion\",\n"
                         "        \"itemTextColor\": \"0xFF919AFF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  },\n"
                         "  {\n"
                         "    \"Category\": \"Sniper\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 103001,\n"
                         "        \"itemClass\": \"BP_Sniper_Kar98k_Wrapper_C_1\",\n"
                         "        \"itemName\": \"Kar98K\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 103002,\n"
                         "        \"itemClass\": \"BP_Sniper_M24_Wrapper_C_1\",\n"
                         "        \"itemName\": \"M24\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 103003,\n"
                         "        \"itemClass\": \"BP_Sniper_AWM_Wrapper_C_1\",\n"
                         "        \"itemName\": \"AWM\",\n"
                         "        \"itemTextColor\": \"0xFFFF66C9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 103004,\n"
                         "        \"itemClass\": \"BP_Sniper_SKS_Wrapper_C_1\",\n"
                         "        \"itemName\": \"SKS\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 103005,\n"
                         "        \"itemClass\": \"BP_Sniper_VSS_Wrapper_C_1\",\n"
                         "        \"itemName\": \"VSS\",\n"
                         "        \"itemTextColor\": \"0xFF919AFF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 103006,\n"
                         "        \"itemClass\": \"BP_Sniper_Mini14_Wrapper_C_1\",\n"
                         "        \"itemName\": \"Mini14\",\n"
                         "        \"itemTextColor\": \"0xFFD1EEEE\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 103007,\n"
                         "        \"itemClass\": \"BP_WEP_Mk14_Pickup_C_1\",\n"
                         "        \"itemName\": \"Mk14\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 103008,\n"
                         "        \"itemClass\": \"BP_Sniper_Win94_Wrapper_C_1\",\n"
                         "        \"itemName\": \"Win94\",\n"
                         "        \"itemTextColor\": \"0xFFF8FAB9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 103009,\n"
                         "        \"itemClass\": \"BP_Sniper_SLR_Wrapper_C_1\",\n"
                         "        \"itemName\": \"SLR\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 103010,\n"
                         "        \"itemClass\": \"BP_Sniper_QBU_Wrapper_C_1\",\n"
                         "        \"itemName\": \"QBU\",\n"
                         "        \"itemTextColor\": \"0xFFD1EEEE\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 103011,\n"
                         "        \"itemClass\": \"BP_Sniper_Mosin_Wrapper_C_1\",\n"
                         "        \"itemName\": \"Mosin Nagant Sniper Rifle\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 103100,\n"
                         "        \"itemClass\": \"BP_Sniper_MK12_Wrapper_C_1\",\n"
                         "        \"itemName\": \"Mk12\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  },\n"
                         "  {\n"
                         "    \"Category\": \"ShotGun\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 104001,\n"
                         "        \"itemClass\": \"BP_ShotGun_S686_Wrapper_C_1\",\n"
                         "        \"itemName\": \"S686\",\n"
                         "        \"itemTextColor\": \"0xFFFF66C9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 104002,\n"
                         "        \"itemClass\": \"BP_ShotGun_S1897_Wrapper_C_1\",\n"
                         "        \"itemName\": \"S1897\",\n"
                         "        \"itemTextColor\": \"0xFFFF66C9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 104003,\n"
                         "        \"itemClass\": \"BP_ShotGun_S12K_Wrapper_C_1\",\n"
                         "        \"itemName\": \"S12K\",\n"
                         "        \"itemTextColor\": \"0xFFFF66C9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 104004,\n"
                         "        \"itemClass\": \"BP_ShotGun_DP12_Wrapper_C_1\",\n"
                         "        \"itemName\": \"DP12\",\n"
                         "        \"itemTextColor\": \"0xFFFF66C9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 104101,\n"
                         "        \"itemClass\": \"BP_ShotGun_M1014_Wrapper_C_1\",\n"
                         "        \"itemName\": \"M1014 Shotgun\",\n"
                         "        \"itemTextColor\": \"0xFFFF66C9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 106006,\n"
                         "        \"itemClass\": \"BP_ShotGun_SawedOff_Wrapper_C_1\",\n"
                         "        \"itemName\": \"Sawed-off\",\n"
                         "        \"itemTextColor\": \"0xFFFF66C9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  },\n"
                         "  {\n"
                         "    \"Category\": \"Pistol\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 106001,\n"
                         "        \"itemClass\": \"BP_Pistol_P92_Wrapper_C_1\",\n"
                         "        \"itemName\": \"P92\",\n"
                         "        \"itemTextColor\": \"0xFF919AFF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 106002,\n"
                         "        \"itemClass\": \"BP_Pistol_P1911_Wrapper_C_1\",\n"
                         "        \"itemName\": \"P1911\",\n"
                         "        \"itemTextColor\": \"0xFFF8FAB9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 106003,\n"
                         "        \"itemClass\": \"BP_Pistol_R1895_Wrapper_C_1\",\n"
                         "        \"itemName\": \"R1895\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 106004,\n"
                         "        \"itemClass\": \"BP_Pistol_P18C_Wrapper_C_1\",\n"
                         "        \"itemName\": \"P18C\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 106005,\n"
                         "        \"itemClass\": \"BP_Pistol_R45_Wrapper_C_1\",\n"
                         "        \"itemName\": \"R45\",\n"
                         "        \"itemTextColor\": \"0xFFF8FAB9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 106008,\n"
                         "        \"itemClass\": \"BP_Pistol_Vz61_Wrapper_C_1\",\n"
                         "        \"itemName\": \"Vz61\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 106010,\n"
                         "        \"itemClass\": \"BP_Pistol_DesertEagle_Wrapper_C_1\",\n"
                         "        \"itemName\": \"Desert Eagle\",\n"
                         "        \"itemTextColor\": \"0xFFF8FAB9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  },\n"
                         "  {\n"
                         "    \"Category\": \"Other\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 107001,\n"
                         "        \"itemClass\": \"BP_Other_CrossBow_Wrapper_C_1\",\n"
                         "        \"itemName\": \"Crossbow\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  },\n"
                         "  {\n"
                         "    \"Category\": \"Melee\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 108001,\n"
                         "        \"itemClass\": \"BP_WEP_Machete_Pickup_C_1\",\n"
                         "        \"itemName\": \"Machete\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 108002,\n"
                         "        \"itemClass\": \"BP_WEP_Cowbar_Pickup_C_1\",\n"
                         "        \"itemName\": \"Crowbar\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 108003,\n"
                         "        \"itemClass\": \"BP_WEP_Sickle_Pickup_C_1\",\n"
                         "        \"itemName\": \"Sickle\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 108004,\n"
                         "        \"itemClass\": \"BP_WEP_Pan_Pickup_C_1\",\n"
                         "        \"itemName\": \"Pan\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  },\n"
                         "  {\n"
                         "    \"Category\": \"Attachment\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 201001,\n"
                         "        \"itemClass\": \"BP_QK_Choke_Pickup_C_1\",\n"
                         "        \"itemName\": \"Choke\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 201002,\n"
                         "        \"itemClass\": \"BP_QK_Mid_Compensator_Pickup_C_1\",\n"
                         "        \"itemName\": \"Compensator (SMG)\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 201003,\n"
                         "        \"itemClass\": \"BP_QK_Sniper_Compensator_Pickup_C_1\",\n"
                         "        \"itemName\": \"Compensator (Snipers)\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 201004,\n"
                         "        \"itemClass\": \"BP_QK_Mid_FlashHider_Pickup_C_1\",\n"
                         "        \"itemName\": \"Flash Hider (SMG)\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 201005,\n"
                         "        \"itemClass\": \"BP_QK_Sniper_FlashHider_Pickup_C_1\",\n"
                         "        \"itemName\": \"Flash Hider (Snipers)\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 201006,\n"
                         "        \"itemClass\": \"BP_QK_Mid_Suppressor_Pickup_C_1\",\n"
                         "        \"itemName\": \"Suppressor (SMG)\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 201007,\n"
                         "        \"itemClass\": \"BP_QK_Sniper_Suppressor_Pickup_C_1\",\n"
                         "        \"itemName\": \"Suppressor (Snipers)\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 201009,\n"
                         "        \"itemClass\": \"BP_QK_Large_Compensator_Pickup_C_1\",\n"
                         "        \"itemName\": \"Compensator (AR)\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 201010,\n"
                         "        \"itemClass\": \"BP_QK_Large_FlashHider_Pickup_C_1\",\n"
                         "        \"itemName\": \"Flash Hider (AR)\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 201011,\n"
                         "        \"itemClass\": \"BP_QK_Large_Suppressor_Pickup_C_1\",\n"
                         "        \"itemName\": \"Suppressor (AR)\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 201012,\n"
                         "        \"itemClass\": \"BP_QK_DuckBill_Pickup_C_1\",\n"
                         "        \"itemName\": \"Duckbill (Shotguns)\",\n"
                         "        \"itemTextColor\": \"0xFFFF66C9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 202001,\n"
                         "        \"itemClass\": \"BP_WB_Angled_Pickup_C_1\",\n"
                         "        \"itemName\": \"Angled Foregrip\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 202002,\n"
                         "        \"itemClass\": \"BP_WB_Vertical_Pickup_C_1\",\n"
                         "        \"itemName\": \"Vertical Foregrip\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 202004,\n"
                         "        \"itemClass\": \"BP_WB_LightGrip_Pickup_C_1\",\n"
                         "        \"itemName\": \"Light Grip\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 202005,\n"
                         "        \"itemClass\": \"BP_WB_HalfGrip_Pickup_C_1\",\n"
                         "        \"itemName\": \"Half Grip\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 202006,\n"
                         "        \"itemClass\": \"BP_WB_ThumbGrip_Pickup_C_1\",\n"
                         "        \"itemName\": \"Thumb Grip\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 202007,\n"
                         "        \"itemClass\": \"BP_WB_Lasersight_Pickup_C_1\",\n"
                         "        \"itemName\": \"Laser Sight\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 203001,\n"
                         "        \"itemClass\": \"BP_MZJ_HD_Pickup_C_1\",\n"
                         "        \"itemName\": \"Red Dot Sight\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 203002,\n"
                         "        \"itemClass\": \"BP_MZJ_QX_Pickup_C_1\",\n"
                         "        \"itemName\": \"Holographic Sight\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 203003,\n"
                         "        \"itemClass\": \"BP_MZJ_2X_Pickup_C_1\",\n"
                         "        \"itemName\": \"2x Scope\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 203004,\n"
                         "        \"itemClass\": \"BP_MZJ_4X_Pickup_C_1\",\n"
                         "        \"itemName\": \"4x Scope\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 203005,\n"
                         "        \"itemClass\": \"BP_MZJ_8X_Pickup_C_1\",\n"
                         "        \"itemName\": \"8x Scope\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 203014,\n"
                         "        \"itemClass\": \"BP_MZJ_3X_Pickup_C_1\",\n"
                         "        \"itemName\": \"3x Scope\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 203015,\n"
                         "        \"itemClass\": \"BP_MZJ_6X_Pickup_C_1\",\n"
                         "        \"itemName\": \"6x Scope\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 203018,\n"
                         "        \"itemClass\": \"BP_MZJ_SideRMR_Pickup_C_1\",\n"
                         "        \"itemName\": \"Canted Sight\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 204014,\n"
                         "        \"itemClass\": \"BP_ZDD_Sniper_Pickup_C_1\",\n"
                         "        \"itemName\": \"Bullet Loop (Shotguns, Sniper Rifles)\",\n"
                         "        \"itemTextColor\": \"0xFFFF66C9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 205001,\n"
                         "        \"itemClass\": \"BP_QT_UZI_Pickup_C_1\",\n"
                         "        \"itemName\": \"Stock (Micro UZI)\",\n"
                         "        \"itemTextColor\": \"0xFF919AFF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 205002,\n"
                         "        \"itemClass\": \"BP_QT_A_Pickup_C_1\",\n"
                         "        \"itemName\": \"Tactical Stock (Rifles, SMG)\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 205003,\n"
                         "        \"itemClass\": \"BP_QT_Sniper_Pickup_C_1\",\n"
                         "        \"itemName\": \"Cheek Pad (Snipers)\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 205004,\n"
                         "        \"itemClass\": \"BP_ZDD_Crossbow_Q_Pickup_C_1\",\n"
                         "        \"itemName\": \"Quiver (Crossbow)\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  },\n"
                         "  {\n"
                         "    \"Category\": \"Mag\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 204004,\n"
                         "        \"itemClass\": \"BP_DJ_Mid_E_Pickup_C_1\",\n"
                         "        \"itemName\": \"Extended Mag (SMG, Pistols)\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 204005,\n"
                         "        \"itemClass\": \"BP_DJ_Mid_Q_Pickup_C_1\",\n"
                         "        \"itemName\": \"Quickdraw Mag (SMG, Pistols)\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 204006,\n"
                         "        \"itemClass\": \"BP_DJ_Mid_EQ_Pickup_C_1\",\n"
                         "        \"itemName\": \"Extended Quickdraw Mag (SMG, Pistols)\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 204007,\n"
                         "        \"itemClass\": \"BP_DJ_Sniper_E_Pickup_C_1\",\n"
                         "        \"itemName\": \"Extended Mag (Snipers)\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 204008,\n"
                         "        \"itemClass\": \"BP_DJ_Sniper_Q_Pickup_C_1\",\n"
                         "        \"itemName\": \"Quickdraw Mag (Snipers)\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 204009,\n"
                         "        \"itemClass\": \"BP_DJ_Sniper_EQ_Pickup_C_1\",\n"
                         "        \"itemName\": \"Extended Quickdraw Mag (Snipers)\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 204011,\n"
                         "        \"itemClass\": \"BP_DJ_Large_E_Pickup_C_1\",\n"
                         "        \"itemName\": \"Extended Quickdraw Mag (AR)\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 204012,\n"
                         "        \"itemClass\": \"BP_DJ_Large_Q_Pickup_C_1\",\n"
                         "        \"itemName\": \"Quickdraw Mag (AR)\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 204013,\n"
                         "        \"itemClass\": \"BP_DJ_Large_EQ_Pickup_C_1\",\n"
                         "        \"itemName\": \"Extended Quickdraw Mag (AR)\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  },\n"
                         "  {\n"
                         "    \"Category\": \"Ammo\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 301001,\n"
                         "        \"itemClass\": \"BP_Ammo_9mm_Pickup_C_1\",\n"
                         "        \"itemName\": \"9mm\",\n"
                         "        \"itemTextColor\": \"0xFF919AFF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 302001,\n"
                         "        \"itemClass\": \"BP_Ammo_762mm_Pickup_C_1\",\n"
                         "        \"itemName\": \"7.62mm\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 303001,\n"
                         "        \"itemClass\": \"BP_Ammo_556mm_Pickup_C_1\",\n"
                         "        \"itemName\": \"5.56mm\",\n"
                         "        \"itemTextColor\": \"0xFFD1EEEE\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 304001,\n"
                         "        \"itemClass\": \"BP_Ammo_12Guage_Pickup_C_1\",\n"
                         "        \"itemName\": \"12 Gauge\",\n"
                         "        \"itemTextColor\": \"0xFFFF66C9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 305001,\n"
                         "        \"itemClass\": \"BP_Ammo_45ACP_Pickup_C_1\",\n"
                         "        \"itemName\": \".45 ACP\",\n"
                         "        \"itemTextColor\": \"0xFFF8FAB9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 306001,\n"
                         "        \"itemClass\": \"BP_Ammo_300Magnum_Pickup_C_1\",\n"
                         "        \"itemName\": \".300 Magnum\",\n"
                         "        \"itemTextColor\": \"0xFFFF66C9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 307001,\n"
                         "        \"itemClass\": \"BP_Ammo_Bolt_Pickup_C_1\",\n"
                         "        \"itemName\": \"Bolt\",\n"
                         "        \"itemTextColor\": \"0xFFFF66C9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  },\n"
                         "  {\n"
                         "    \"Category\": \"Bag\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 501001,\n"
                         "        \"itemClass\": \"PickUp_BP_Bag_Lv1_C_1\",\n"
                         "        \"itemName\": \"Backpack (Lv. 1)\",\n"
                         "        \"itemTextColor\": \"0xFFFFF266\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 501002,\n"
                         "        \"itemClass\": \"PickUp_BP_Bag_Lv2_C_1\",\n"
                         "        \"itemName\": \"Backpack (Lv. 2)\",\n"
                         "        \"itemTextColor\": \"0xFFFFF266\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 501006,\n"
                         "        \"itemClass\": \"PickUp_BP_Bag_Lv3_B_C_1\",\n"
                         "        \"itemName\": \"Backpack (Lv. 3)\",\n"
                         "        \"itemTextColor\": \"0xFFFFF266\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  },\n"
                         "  {\n"
                         "    \"Category\": \"Helmet\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 502001,\n"
                         "        \"itemClass\": \"PickUp_BP_Helmet_Lv1_C_1\",\n"
                         "        \"itemName\": \"Motorcycle Helmet (Lv. 1)\",\n"
                         "        \"itemTextColor\": \"0xFFFFF266\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 502002,\n"
                         "        \"itemClass\": \"PickUp_BP_Helmet_Lv2_C_1\",\n"
                         "        \"itemName\": \"Military Helmet (Lv. 2)\",\n"
                         "        \"itemTextColor\": \"0xFFFFF266\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 502003,\n"
                         "        \"itemClass\": \"PickUp_BP_Helmet_Lv3_C_1\",\n"
                         "        \"itemName\": \"Spetsnaz Helmet (Lv. 3)\",\n"
                         "        \"itemTextColor\": \"0xFFFFF266\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  },\n"
                         "  {\n"
                         "    \"Category\": \"Armor\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 503001,\n"
                         "        \"itemClass\": \"PickUp_BP_Armor_Lv1_C_1\",\n"
                         "        \"itemName\": \"Police Vest (Lv. 1)\",\n"
                         "        \"itemTextColor\": \"0xFFFFF266\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 503002,\n"
                         "        \"itemClass\": \"PickUp_BP_Armor_Lv2_C_1\",\n"
                         "        \"itemName\": \"Police Vest (Lv. 2)\",\n"
                         "        \"itemTextColor\": \"0xFFFFF266\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 503003,\n"
                         "        \"itemClass\": \"PickUp_BP_Armor_Lv3_C_1\",\n"
                         "        \"itemName\": \"Military Vest (Lv. 3)\",\n"
                         "        \"itemTextColor\": \"0xFFFFF266\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  },\n"
                         "  {\n"
                         "    \"Category\": \"Medic\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 601001,\n"
                         "        \"itemClass\": \"Drink_Pickup_C_1\",\n"
                         "        \"itemName\": \"Energy Drink\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 601002,\n"
                         "        \"itemClass\": \"Injection_Pickup_C_1\",\n"
                         "        \"itemName\": \"Adrenaline Syringe\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 601003,\n"
                         "        \"itemClass\": \"Pills_Pickup_C_1\",\n"
                         "        \"itemName\": \"Painkiller\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 601004,\n"
                         "        \"itemClass\": \"Bandage_Pickup_C_1\",\n"
                         "        \"itemName\": \"Bandage\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 601005,\n"
                         "        \"itemClass\": \"Firstaid_Pickup_C_1\",\n"
                         "        \"itemName\": \"First Aid Kit\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 601006,\n"
                         "        \"itemClass\": \"FirstAidbox_Pickup_C_1\",\n"
                         "        \"itemName\": \"Med Kit\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  }\n"
                         "]";